export default {
  en: {
    8: { caps: 'Backspace', lit: 'Backspace', onShift: ' ' },
    9: { caps: 'tab', lit: 'tab', onShift: ' ' },
    13: { caps: 'enter', lit: 'enter', onShift: ' ' },
    16: { caps: 'shift', lit: 'shift', onShift: ' ' },
    17: { caps: 'ctrl', lit: 'ctrl', onShift: ' ' },
    18: { caps: 'alt', lit: 'alt', onShift: ' ' },
    20: { caps: 'caps lock', lit: 'caps lock', onShift: ' ' },
    32: { caps: ' ', lit: ' ', onShift: ' ' },
    37: { caps: '', lit: '', onShift: ' ' },
    38: { caps: '', lit: '', onShift: ' ' },
    39: { caps: '', lit: '', onShift: ' ' },
    40: { caps: '', lit: '', onShift: ' ' },
    91: { caps: 'Win', lit: 'Win', onShift: ' ' },
    46: { caps: 'DEL', lit: 'DEL', onShift: ' ' },
    49: { caps: '1', lit: '1', onShift: ' ' },
    50: { caps: '2', lit: '2', onShift: ' ' },
    51: { caps: '3', lit: '3', onShift: ' ' },
    52: { caps: '4', lit: '4', onShift: ' ' },
    53: { caps: '5', lit: '5', onShift: ' ' },
    54: { caps: '6', lit: '6', onShift: ' ' },
    55: { caps: '7', lit: '7', onShift: ' ' },
    56: { caps: '8', lit: '8', onShift: ' ' },
    57: { caps: '9', lit: '9', onShift: ' ' },
    48: { caps: '0', lit: '0', onShift: ' ' },
    189: { caps: '-', lit: '-', onShift: '_' },
    187: { caps: '=', lit: '=', onShift: '+' },
    65: { caps: 'A', lit: 'a', onShift: ' ' },
    66: { caps: 'B', lit: 'b', onShift: ' ' },
    67: { caps: 'C', lit: 'c', onShift: ' ' },
    68: { caps: 'D', lit: 'd', onShift: ' ' },
    69: { caps: 'E', lit: 'e', onShift: ' ' },
    70: { caps: 'F', lit: 'f', onShift: ' ' },
    71: { caps: 'G', lit: 'g', onShift: ' ' },
    72: { caps: 'H', lit: 'h', onShift: ' ' },
    73: { caps: 'I', lit: 'i', onShift: ' ' },
    74: { caps: 'J', lit: 'j', onShift: ' ' },
    75: { caps: 'K', lit: 'k', onShift: ' ' },
    76: { caps: 'L', lit: 'l', onShift: ' ' },
    77: { caps: 'M', lit: 'm', onShift: ' ' },
    78: { caps: 'N', lit: 'n', onShift: ' ' },
    79: { caps: 'O', lit: 'o', onShift: ' ' },
    80: { caps: 'P', lit: 'p', onShift: ' ' },
    81: { caps: 'Q', lit: 'q', onShift: ' ' },
    82: { caps: 'R', lit: 'r', onShift: ' ' },
    83: { caps: 'S', lit: 's', onShift: ' ' },
    84: { caps: 'T', lit: 't', onShift: ' ' },
    85: { caps: 'U', lit: 'u', onShift: ' ' },
    86: { caps: 'V', lit: 'v', onShift: ' ' },
    87: { caps: 'W', lit: 'w', onShift: ' ' },
    88: { caps: 'X', lit: 'x', onShift: ' ' },
    89: { caps: 'Y', lit: 'y', onShift: ' ' },
    90: { caps: 'Z', lit: 'z', onShift: ' ' },
    186: { caps: ';', lit: ';', onShift: ' ' },
    188: { caps: ',', lit: ',', onShift: ' ' },
    190: { caps: '.', lit: '.', onShift: ' ' },
    191: { caps: '/', lit: '/', onShift: ' ' },
    192: { caps: '`', lit: '`', onShift: ' ' },
    219: { caps: '[', lit: '[', onShift: ' ' },
    220: { caps: '\\', lit: '\\', onShift: ' ' },
    221: { caps: ']', lit: ']', onShift: ' ' },
    222: { caps: "'", lit: "'", onShift: ' ' },
  },

  ru: {
    8: { caps: 'Backspace', lit: 'Backspace', onShift: ' ' },
    9: { caps: 'tab', lit: 'tab', onShift: ' ' },
    13: { caps: 'enter', lit: 'enter', onShift: ' ' },
    16: { caps: 'shift', lit: 'shift', onShift: ' ' },
    17: { caps: 'ctrl', lit: 'ctrl', onShift: ' ' },
    18: { caps: 'alt', lit: 'alt', onShift: ' ' },
    20: { caps: 'caps lock', lit: 'caps lock', onShift: ' ' },
    37: { caps: '', lit: '', onShift: ' ' },
    38: { caps: '', lit: '', onShift: ' ' },
    39: { caps: '', lit: '', onShift: ' ' },
    40: { caps: '', lit: '', onShift: ' ' },
    91: { caps: 'Win', lit: 'Win', onShift: ' ' },
    46: { caps: 'DEL', lit: 'DEL', onShift: ' ' },
    32: { caps: ' ', lit: ' ', onShift: ' ' },
    49: { caps: '1', lit: '1', onShift: ' ' },
    50: { caps: '2', lit: '2', onShift: ' ' },
    51: { caps: '3', lit: '3', onShift: ' ' },
    52: { caps: '4', lit: '4', onShift: ' ' },
    53: { caps: '5', lit: '5', onShift: ' ' },
    54: { caps: '6', lit: '6', onShift: ' ' },
    55: { caps: '7', lit: '7', onShift: ' ' },
    56: { caps: '8', lit: '8', onShift: ' ' },
    57: { caps: '9', lit: '9', onShift: ' ' },
    48: { caps: '0', lit: '0', onShift: ' ' },
    65: { caps: 'Ф', lit: 'ф', onShift: ' ' },
    66: { caps: 'И', lit: 'и', onShift: ' ' },
    67: { caps: 'С', lit: 'с', onShift: ' ' },
    68: { caps: 'В', lit: 'в', onShift: ' ' },
    69: { caps: 'У', lit: 'у', onShift: ' ' },
    70: { caps: 'А', lit: 'а', onShift: ' ' },
    71: { caps: 'П', lit: 'п', onShift: ' ' },
    72: { caps: 'Р', lit: 'р', onShift: ' ' },
    73: { caps: 'Ш', lit: 'ш', onShift: ' ' },
    74: { caps: 'О', lit: 'о', onShift: ' ' },
    75: { caps: 'Л', lit: 'л', onShift: ' ' },
    76: { caps: 'Д', lit: 'д', onShift: ' ' },
    77: { caps: 'Ь', lit: 'ь', onShift: ' ' },
    78: { caps: 'Т', lit: 'т', onShift: ' ' },
    79: { caps: 'Щ', lit: 'щ', onShift: ' ' },
    80: { caps: 'З', lit: 'з', onShift: ' ' },
    81: { caps: 'Й', lit: 'й', onShift: ' ' },
    82: { caps: 'К', lit: 'к', onShift: ' ' },
    83: { caps: 'Ы', lit: 'ы', onShift: ' ' },
    84: { caps: 'Е', lit: 'е', onShift: ' ' },
    85: { caps: 'Г', lit: 'г', onShift: ' ' },
    86: { caps: 'М', lit: 'м', onShift: ' ' },
    87: { caps: 'Ц', lit: 'ц', onShift: ' ' },
    88: { caps: 'Ч', lit: 'ч', onShift: ' ' },
    89: { caps: 'Н', lit: 'н', onShift: ' ' },
    90: { caps: 'Я', lit: 'я', onShift: ' ' },
    186: { caps: 'Ж', lit: 'ж', onShift: ' ' },
    189: { caps: '-', lit: '-', onShift: '_' },
    187: { caps: '=', lit: '=', onShift: '+' },
    188: { caps: 'Б', lit: 'б', onShift: ' ' },
    190: { caps: 'Ю', lit: 'ю', onShift: ' ' },
    191: { caps: '.', lit: '.', onShift: ' ' },
    192: { caps: 'Ё', lit: 'ё', onShift: ' ' },
    219: { caps: 'Х', lit: 'х', onShift: ' ' },
    220: { caps: '\\', lit: '\\', onShift: ' ' },
    221: { caps: 'Ъ', lit: 'ъ', onShift: ' ' },
    222: { caps: 'Э', lit: 'э', onShift: ' ' },
  },
};
